### ISSUE TITLE
[New project] WizardSwap

### ISSUE THREAD

**Issue by localparticl-com** [particl-page/particl.page#5]
- **Project name:** WizardSwap
- **Short summary:** Non-custodial trading platform.
- **Homepage:** https://www.wizardswap.io
- **Development:** Private

### [WizardSwap.io](https://www.wizardswap.io) is the simplest way to exchange Particl with other cryptocurrencies.

* No sign-ups required.
* Tor browser support ([link](http://wizardswgtu2ovor7r2esg3cxdpt7tv4nrugi32lldv53zmtonbz6sid.onion/)).
* Fixed pricing.
* Live customer service.

[![ws-preview](https://user-images.githubusercontent.com/75868014/110841256-854cc300-825a-11eb-8809-c11f378d9c17.png)](https://www.wizardswap.io)

Unlike many other swapping platforms out there, [WizardSwap](https://www.wizardswap.io) does not interact with any exchange order books so orders have no influence on any exchange prices. Instead it draws liquidity directly from [localparticl.com](https://www.localparticl.com) users who have deposited funds and opted to enable swaps. Pricing is based on a global average plus the margins liquidity providers have set.

**Comment by xe-nonymous** [comment]
Merged & online. Thanks very much!
